# Generated by Django 3.2.13 on 2023-06-20 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='owner',
            new_name='created_by',
        ),
    ]
